const snakeLevels = {
  ar: [
    ["أول لقمة", "الحيطان بتلف بيك للناحية التانية. كُل وكبر."],
    ["السور", "دلوقتي فيه سور. ولو صاحبك خبط، روح على 🆘 ترجّعه ببلاش."],
    ["الأعمدة", "لف بين الأعمدة من غير ما تخبط."],
    ["البوابات", "السور قاسم الخريطة نصين. ادخل الدوامة تطلع من الناحية التانية."],
    ["حمى الدهب", "🌟 بتلاتة. بس مش هتستناك كتير."],
    ["الفطر المجنون", "🍄 بيعكس الاتجاهات كام ثانية. ابعد عنه."],
    ["حقل الألغام", "إوعى تلمس 💣."],
    ["الحراس", "👾 بيلفوا في الصفوف ولو لمسوا ديلك بيقطعوه."],
    ["الخزنة", "الفاكهة جوه الخزنة. اقفوا على الزرارين 🔘 مع بعض عشان الباب يفتح."],
    ["الضلمة", "مش شايف غير اللي حوالين راسك."],
    ["المتاهة", "لاقي طريقك جوه المتاهة."],
    ["ضد الساعة", "خلّص الهدف قبل الوقت ما يخلص."],
    ["مطر النيازك", "☄️ نازلة من فوق. خلي عينك فوق."],
    ["الحلقة بتقفل", "الملعب بيصغر. لما الأطراف تنوّر أحمر اجري على النص."],
    ["المسكون", "👻 بيطاردوك من جوه الحيطان. متقفش."],
    ["ألغام في الضلمة", "قنابل مش هتشوفها غير وانت قريب منها."],
    ["البرجين", "زرار في كل برج. اتقسموا عشان تفتحوا الخزنة."],
    ["العاصفة", "نيازك وفطر، وأسرع كمان."],
    ["الشبكة", "متاهة ضلمة وفيها شبح."],
    ["التنين", "🐲 عايزك. كُل واطلع سليم."],
  ],
  en: [
    ["First bite", "The edges wrap around. Eat and grow."],
    ["The fence", "Walls now. If your friend crashes, reach the 🆘 to bring them back for free."],
    ["Pillars", "Weave between the pillars."],
    ["Portals", "A wall splits the map. Swirl through a portal to cross."],
    ["Gold rush", "🌟 is worth three, and it won't wait long."],
    ["Crazy mushrooms", "🍄 flips your controls for a few seconds. Avoid it."],
    ["Minefield", "Don't touch the 💣."],
    ["Guards", "👾 patrol the rows and bite off your tail."],
    ["The vault", "The fruit is locked in. Stand on both 🔘 plates together to open the gate."],
    ["Lights out", "You only see around your head."],
    ["The maze", "Find your way round."],
    ["Against the clock", "Hit the goal before time runs out."],
    ["Meteor shower", "☄️ fall from the sky. Watch above you."],
    ["Closing ring", "The arena shrinks. When the edge flashes red, get to the middle."],
    ["Haunted", "👻 hunt you through walls. Keep moving."],
    ["Dark mines", "Bombs you only see up close."],
    ["Two towers", "One plate in each tower. Split up to open the vault."],
    ["The storm", "Meteors and mushrooms, and faster."],
    ["The web", "A dark maze with a ghost in it."],
    ["The dragon", "🐲 wants you. Eat up and get out alive."],
  ],
};

const ar = {
  home: "الرئيسية",
  back: "رجوع",
  mute: "كتم الصوت",
  unmute: "تشغيل الصوت",
  switchLang: "Switch to English",
  score: "النقاط",
  you: "أنت",
  pause: "إيقاف مؤقت",
  paused: "واقفين شوية",
  resume: "كمّل",

  "net.online": "أونلاين",
  "net.lost": "الاتصال اتقطع",
  "net.lostText": "صاحبك خرج أو النت فصل عند حد فيكم.",

  "lobby.title": "هتلعب إزاي؟",
  "lobby.host": "اعمل أوضة",
  "lobby.hostHint": "هتاخد كود تبعته لصاحبك",
  "lobby.join": "ادخل بكود",
  "lobby.joinHint": "صاحبك عمل أوضة وبعتلك الكود",
  "lobby.back": "رجوع",
  "lobby.share": "ابعت الكود",
  "lobby.creating": "بنجهز الأوضة",
  "lobby.waiting": "مستنيين صاحبك",
  "lobby.hostTitle": "الأوضة بتاعتك",
  "lobby.hostText": "ابعت الكود ده لصاحبك، وأول ما يدخل هنبدأ.",
  "lobby.codeLabel": "كود الأوضة",
  "lobby.connect": "ادخل",
  "lobby.connecting": "بندخلك",
  "lobby.joinTitle": "ادخل أوضة صاحبك",
  "lobby.joinText": "اكتب الكود اللي من ٤ حروف.",
  "lobby.shareText": "تعالى نلعب في أركيد الإيموجي! الكود: {code}",
  "lobby.copied": "الرابط اتنسخ، ابعته لصاحبك",
  "lobby.err.network": "مش قادرين نوصل. اتأكد من النت وجرب تاني.",
  "lobby.err.unsupported": "المتصفح ده مش بيدعم اللعب أونلاين.",
  "lobby.err.noRoom": "مفيش أوضة بالكود ده.",
  "lobby.err.timeout": "الاتصال أخد وقت كتير. جرب تاني.",
  "lobby.err.full": "الأوضة مليانة.",
  "lobby.err.short": "الكود ٤ حروف.",

  "hub.pageTitle": "أركيد الإيموجي",
  "hub.brand": "أركيد الإيموجي",
  "hub.title1": "العبوا",
  "hub.title2": "مع بعض.",
  "hub.lead": "أربع ألعاب إيموجي، منهم اتنين أونلاين مع صاحبك. من غير تسجيل، كود وخلاص.",
  "hub.cta": "اختار لعبة",
  "hub.games": "الألعاب",
  "hub.snakeText": "تعبانين في فريق واحد. ٢٠ مرحلة فيها بوابات وأشباح وخزنة مقفولة وتنين.",
  "hub.fourText": "فراولة ضد لمون. رص أربعة قبل صاحبك.",
  "hub.breakoutText": "اللعبة الأصلية. نطّط الإيموجي وكسّر حيطان الفاكهة ودوّر على الأكواد السرية.",
  "hub.memoryText": "بص بسرعة ودوّر على الأزواج. ٨ مراحل، من ٦ كروت لـ٣٦.",
  "hub.tagOnline": "تعاون أونلاين",
  "hub.tagOnline1v1": "أونلاين ١ ضد ١",
  "hub.tag20": "٢٠ مرحلة",
  "hub.tagBot": "ضد البوت",
  "hub.tagEndless": "مراحل مالهاش آخر",
  "hub.tagCodes": "أكواد سرية",
  "hub.tag8": "٨ مراحل",
  "hub.tagStars": "٣ نجوم لكل مرحلة",
  "hub.howTitle": "اللعب أونلاين",
  "hub.how1": "افتح التعبان أو أربعة في صف واضغط «اعمل أوضة».",
  "hub.how2": "ابعت الكود أو الرابط لصاحبك.",
  "hub.how3": "يضغط «ادخل بكود»، وتلعبوا من موبايل لموبايل.",
  "hub.madeBy": "عملها",

  "snake.pageTitle": "تعبان مع بعض",
  "snake.title": "تعبان مع بعض",
  "snake.solo": "العب لوحدك",
  "snake.soloHint": "نفس الـ٢٠ مرحلة، وزرار واحد يكفي لفتح الخزنة",
  "snake.waitHost": "مستنيين صاحبك",
  "snake.waitHostText": "هو اللي بيختار المرحلة. انت التعبان البرتقالي 🟠",
  "snake.coopEyebrow": "أونلاين · انت الأخضر 🟢",
  "snake.soloEyebrow": "لوحدك",
  "snake.pickLevel": "اختار مرحلة",
  "snake.level": "المرحلة",
  "snake.goal": "الهدف",
  "snake.lives": "الأرواح",
  "snake.time": "الوقت",
  "snake.continueFrom": "كمّل من المرحلة {n}",
  "snake.gateOpen": "الخزنة اتفتحت! ادخلوا بسرعة",
  "snake.confused": "💫 الاتجاهات اتعكست",
  "snake.rescued": "🆘 رجّعت صاحبك!",
  "snake.timeUp": "⏱️ الوقت خلص",
  "snake.over": "خلصت الأرواح",
  "snake.overText": "وصلتوا للمرحلة {n} وجمعتوا {score} نقطة.",
  "snake.hostDecides": "صاحبك هيقرر نعيد ولا لأ.",
  "snake.retry": "نعيد المرحلة",
  "snake.won": "خلصتوا الـ٢٠ مرحلة!",
  "snake.wonSolo": "هزمت التنين لوحدك. {score} نقطة.",
  "snake.wonCoop": "هزمتوا التنين مع بعض. {score} نقطة.",
  "snake.goalLine": "الهدف: {goal}.",
  "snake.clear": "المرحلة خلصت!",
  "snake.nextUp": "جاية المرحلة {n}",
  "snake.keepSolo": "كمّل لوحدك",
  "snake.keysHint": "الأسهم أو WASD للتحكم · P للإيقاف",

  "four.pageTitle": "أربعة في صف",
  "four.title": "أربعة في صف",
  "four.bot": "ضد البوت",
  "four.botHint": "بوت بيفكر ٥ خطوات لقدام",
  "four.local": "اتنين على موبايل واحد",
  "four.localHint": "كل واحد يلعب دوره",
  "four.waitHost": "مستنيين صاحبك يبدأ",
  "four.column": "العمود",
  "four.botName": "البوت 🤖",
  "four.player1": "لاعب ١",
  "four.player2": "لاعب ٢",
  "four.friend": "صاحبك",
  "four.draw": "تعادل! الملعب اتملى",
  "four.wins": "{token} كسب!",
  "four.youWin": "كسبت! 🎉",
  "four.botWins": "البوت كسب المرة دي",
  "four.friendWins": "صاحبك كسب",
  "four.again": "جولة تانية",
  "four.botThinking": "البوت بيفكر…",
  "four.turnOf": "دور {token}",
  "four.yourTurn": "دورك {token}",
  "four.friendTurn": "دور صاحبك…",
  "four.playBot": "العب ضد البوت",
  "four.react": "ابعت",

  "memory.pageTitle": "ذاكرة الإيموجي",
  "memory.title": "ذاكرة الإيموجي",
  "memory.eyebrow": "بص بسرعة",
  "memory.pick": "اختار مرحلة",
  "memory.levelPairs": "المرحلة {n} · {pairs} أزواج",
  "memory.card": "كارت {n}",
  "memory.done": "برافو!",
  "memory.allDone": "خلصت كل المراحل!",
  "memory.result": "{moves} محاولة في {time}.",
  "memory.levels": "المراحل",
  "memory.next": "المرحلة الجاية",
  "memory.replay": "أعيدها",
  "memory.level": "المرحلة",
  "memory.moves": "المحاولات",
  "memory.time": "الوقت",

  "breakout.pageTitle": "إيموجي بريك أوت",
  "breakout.title": "إيموجي بريك أوت",
  "breakout.intro": "حرّك المضرب بصباعك أو بالأسهم، ولمسة واحدة تطلق الكورة.",
  "breakout.play": "يلا نلعب",
  "breakout.levelN": "المرحلة {n}",
  "breakout.tapLaunch": "المس عشان تطلق",
  "breakout.over": "خلصت اللعبة",
  "breakout.overText": "جمعت {score} نقطة. أعلى رقم: {best}.",
  "breakout.newBest": "رقم قياسي جديد",
  "breakout.again": "العب تاني",
  "breakout.best": "الأعلى",
  "breakout.level": "المرحلة",
  "breakout.lives": "الأرواح",
  "breakout.codes": "الأكواد السرية",
  "breakout.codePlaceholder": "الكود السري…",
  "breakout.codeOn": "✨ الكود اشتغل",
  "breakout.codeBad": "الكود ده مش صح، جرب تاني",
  "breakout.codePlayFirst": "ابدأ اللعب الأول",
  "breakout.power.wide": "مضرب عريض",
  "breakout.power.fire": "كورة نار",
  "breakout.power.multi": "كور زيادة",
  "breakout.power.slow": "بطيء",
  "breakout.power.life": "روح زيادة",
};

const en = {
  home: "Home",
  back: "Back",
  mute: "Mute",
  unmute: "Unmute",
  switchLang: "التبديل للعربية",
  score: "Score",
  you: "You",
  pause: "Pause",
  paused: "Paused",
  resume: "Resume",

  "net.online": "Online",
  "net.lost": "Connection lost",
  "net.lostText": "Your friend left, or someone's internet dropped.",

  "lobby.title": "How do you want to play?",
  "lobby.host": "Create a room",
  "lobby.hostHint": "Get a code to send your friend",
  "lobby.join": "Join with a code",
  "lobby.joinHint": "Your friend made a room and sent a code",
  "lobby.back": "Back",
  "lobby.share": "Send the code",
  "lobby.creating": "Setting up the room",
  "lobby.waiting": "Waiting for your friend",
  "lobby.hostTitle": "Your room",
  "lobby.hostText": "Send this code to your friend. The game starts as soon as they join.",
  "lobby.codeLabel": "Room code",
  "lobby.connect": "Join",
  "lobby.connecting": "Joining",
  "lobby.joinTitle": "Join your friend's room",
  "lobby.joinText": "Type the four-letter code.",
  "lobby.shareText": "Come play Emoji Arcade with me! Code: {code}",
  "lobby.copied": "Link copied. Send it to your friend",
  "lobby.err.network": "Couldn't connect. Check your internet and try again.",
  "lobby.err.unsupported": "This browser can't play online.",
  "lobby.err.noRoom": "No room with that code.",
  "lobby.err.timeout": "That took too long. Try again.",
  "lobby.err.full": "That room is full.",
  "lobby.err.short": "The code is four letters.",

  "hub.pageTitle": "Emoji Arcade",
  "hub.brand": "Emoji Arcade",
  "hub.title1": "Play",
  "hub.title2": "together.",
  "hub.lead": "Four emoji games, two of them online with a friend. No sign-up, just a room code.",
  "hub.cta": "Pick a game",
  "hub.games": "Games",
  "hub.snakeText": "Two snakes, one team. Twenty levels of portals, ghosts, locked vaults and a dragon.",
  "hub.fourText": "Strawberries against lemons. Line up four before your friend does.",
  "hub.breakoutText": "The original. Bounce an emoji through fruit walls and find the secret codes.",
  "hub.memoryText": "Look fast, then find the pairs. Eight boards, from six cards to thirty-six.",
  "hub.tagOnline": "Online co-op",
  "hub.tagOnline1v1": "Online 1v1",
  "hub.tag20": "20 levels",
  "hub.tagBot": "vs bot",
  "hub.tagEndless": "Endless levels",
  "hub.tagCodes": "Secret codes",
  "hub.tag8": "8 levels",
  "hub.tagStars": "3 stars each",
  "hub.howTitle": "Playing online",
  "hub.how1": "Open Snake or Four in a Row and tap “Create a room”.",
  "hub.how2": "Send the code or the link to your friend.",
  "hub.how3": "They tap “Join with a code”, and you play phone to phone.",
  "hub.madeBy": "Made by",

  "snake.pageTitle": "Snake Together",
  "snake.title": "Snake Together",
  "snake.solo": "Play alone",
  "snake.soloHint": "The same 20 levels; one plate is enough to open a vault",
  "snake.waitHost": "Waiting for your friend",
  "snake.waitHostText": "They pick the level. You are the orange snake 🟠",
  "snake.coopEyebrow": "Online · you are green 🟢",
  "snake.soloEyebrow": "Solo",
  "snake.pickLevel": "Pick a level",
  "snake.level": "Level",
  "snake.goal": "Goal",
  "snake.lives": "Lives",
  "snake.time": "Time",
  "snake.continueFrom": "Continue from level {n}",
  "snake.gateOpen": "The vault is open! Get in",
  "snake.confused": "💫 Controls flipped",
  "snake.rescued": "🆘 You saved your friend!",
  "snake.timeUp": "⏱️ Time's up",
  "snake.over": "Out of lives",
  "snake.overText": "You reached level {n} with {score} points.",
  "snake.hostDecides": "Your friend decides what's next.",
  "snake.retry": "Retry the level",
  "snake.won": "All 20 levels done!",
  "snake.wonSolo": "You beat the dragon on your own. {score} points.",
  "snake.wonCoop": "You beat the dragon together. {score} points.",
  "snake.goalLine": "Goal: {goal}.",
  "snake.clear": "Level clear!",
  "snake.nextUp": "Level {n} is next",
  "snake.keepSolo": "Keep playing alone",
  "snake.keysHint": "Arrows or WASD to steer · P to pause",

  "four.pageTitle": "Four in a Row",
  "four.title": "Four in a Row",
  "four.bot": "Against the bot",
  "four.botHint": "It thinks five moves ahead",
  "four.local": "Two on one phone",
  "four.localHint": "Take turns",
  "four.waitHost": "Waiting for your friend to start",
  "four.column": "Column",
  "four.botName": "Bot 🤖",
  "four.player1": "Player 1",
  "four.player2": "Player 2",
  "four.friend": "Friend",
  "four.draw": "Draw! The board is full",
  "four.wins": "{token} wins!",
  "four.youWin": "You win! 🎉",
  "four.botWins": "The bot wins this one",
  "four.friendWins": "Your friend wins",
  "four.again": "Play again",
  "four.botThinking": "The bot is thinking…",
  "four.turnOf": "{token}'s turn",
  "four.yourTurn": "Your turn {token}",
  "four.friendTurn": "Your friend's turn…",
  "four.playBot": "Play the bot",
  "four.react": "Send",

  "memory.pageTitle": "Emoji Memory",
  "memory.title": "Emoji Memory",
  "memory.eyebrow": "Look fast",
  "memory.pick": "Pick a level",
  "memory.levelPairs": "Level {n} · {pairs} pairs",
  "memory.card": "Card {n}",
  "memory.done": "Nice!",
  "memory.allDone": "Every level done!",
  "memory.result": "{moves} moves in {time}.",
  "memory.levels": "Levels",
  "memory.next": "Next level",
  "memory.replay": "Replay",
  "memory.level": "Level",
  "memory.moves": "Moves",
  "memory.time": "Time",

  "breakout.pageTitle": "Emoji Breakout",
  "breakout.title": "Emoji Breakout",
  "breakout.intro": "Move the paddle with your finger or the arrow keys. One tap launches the ball.",
  "breakout.play": "Let's play",
  "breakout.levelN": "Level {n}",
  "breakout.tapLaunch": "Tap to launch",
  "breakout.over": "Game over",
  "breakout.overText": "You scored {score}. Best: {best}.",
  "breakout.newBest": "New best",
  "breakout.again": "Play again",
  "breakout.best": "Best",
  "breakout.level": "Level",
  "breakout.lives": "Lives",
  "breakout.codes": "Secret codes",
  "breakout.codePlaceholder": "Secret code…",
  "breakout.codeOn": "✨ Code on",
  "breakout.codeBad": "Not a code. Try again",
  "breakout.codePlayFirst": "Start playing first",
  "breakout.power.wide": "Wide paddle",
  "breakout.power.fire": "Fireball",
  "breakout.power.multi": "Extra balls",
  "breakout.power.slow": "Slow motion",
  "breakout.power.life": "Extra life",
};

for (const [lang, table] of [["ar", ar], ["en", en]]) {
  snakeLevels[lang].forEach(([name, hint], i) => {
    table[`snake.l${i + 1}.name`] = name;
    table[`snake.l${i + 1}.hint`] = hint;
  });
}

export const strings = { ar, en };
